version: '3.8'

services:
  # 1. Our PostgreSQL Database (The Bouncer)
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ticket_db
    ports:
      - "5433:5433"

  # 2. Our Redis Cache (The Alarm Clock)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"